module Bestiary::Parsers
end

require 'bestiary/parsers/creature'
require 'bestiary/parsers/name'
require 'bestiary/parsers/cr'
require 'bestiary/parsers/xp'
require 'bestiary/parsers/alignment'
require 'bestiary/parsers/size'
require 'bestiary/parsers/type'
require 'bestiary/parsers/initiative'
require 'bestiary/parsers/senses'
require 'bestiary/parsers/aura'
require 'bestiary/parsers/armor'
require 'bestiary/parsers/dice'
require 'bestiary/parsers/hp'
require 'bestiary/parsers/regeneration'
require 'bestiary/parsers/fast_healing'
require 'bestiary/parsers/fortitude'
require 'bestiary/parsers/reflex'
require 'bestiary/parsers/will'
require 'bestiary/parsers/defensive_abilities'
require 'bestiary/parsers/damage_reduction'
require 'bestiary/parsers/immunities'
require 'bestiary/parsers/resistances'
require 'bestiary/parsers/spell_resistance'
require 'bestiary/parsers/weaknesses'
require 'bestiary/parsers/speed'
